/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package auto.work;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jay Fuego
 */
public class MainPanel extends javax.swing.JFrame {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        this.setResizable(false);
        initComponents();
          this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon(getClass().getResource("Icon/icon.png"));
        idView.setVisible(false);
        plateView.setVisible(true);
        selectedPanel = PlateMenu;
        selectedBorder = PlateSideBorder;
        mainViewPanel = plateView;
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        LogoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        PlateMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PlateSideBorder = new javax.swing.JPanel();
        IdMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        idSideBorder = new javax.swing.JPanel();
        Mainview = new javax.swing.JPanel();
        plateView = new javax.swing.JPanel();
        idView = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        im1 = new javax.swing.JLabel();
        im2 = new javax.swing.JLabel();
        im3 = new javax.swing.JLabel();
        im4 = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();
        uploadBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auto Worker by: Jay Fuego");
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        sidePanel.setBackground(new java.awt.Color(56, 23, 62));
        sidePanel.setPreferredSize(new java.awt.Dimension(250, 500));
        sidePanel.setLayout(new java.awt.BorderLayout());

        LogoPanel.setBackground(new java.awt.Color(56, 23, 62));
        LogoPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auto/work/Icon/icons8-ai-100.png"))); // NOI18N
        LogoPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        sidePanel.add(LogoPanel, java.awt.BorderLayout.PAGE_START);

        MenuPanel.setBackground(new java.awt.Color(56, 23, 62));

        PlateMenu.setBackground(new java.awt.Color(169, 71, 187));
        PlateMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        PlateMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlateMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PlateMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PlateMenuMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auto/work/Icon/icons8-id-24.png"))); // NOI18N
        jLabel2.setText("Plate");
        jLabel2.setAlignmentX(1.0F);
        jLabel2.setIconTextGap(10);
        jLabel2.setPreferredSize(new java.awt.Dimension(140, 50));

        javax.swing.GroupLayout PlateMenuLayout = new javax.swing.GroupLayout(PlateMenu);
        PlateMenu.setLayout(PlateMenuLayout);
        PlateMenuLayout.setHorizontalGroup(
            PlateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlateMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        PlateMenuLayout.setVerticalGroup(
            PlateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlateMenuLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PlateSideBorder.setBackground(new java.awt.Color(112, 47, 124));
        PlateSideBorder.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout PlateSideBorderLayout = new javax.swing.GroupLayout(PlateSideBorder);
        PlateSideBorder.setLayout(PlateSideBorderLayout);
        PlateSideBorderLayout.setHorizontalGroup(
            PlateSideBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        PlateSideBorderLayout.setVerticalGroup(
            PlateSideBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        IdMenu.setBackground(new java.awt.Color(56, 23, 62));
        IdMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        IdMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IdMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IdMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IdMenuMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auto/work/Icon/icons8-id-24 (1).png"))); // NOI18N
        jLabel3.setText("Identification");
        jLabel3.setAlignmentX(1.0F);
        jLabel3.setIconTextGap(10);
        jLabel3.setPreferredSize(new java.awt.Dimension(140, 50));

        javax.swing.GroupLayout IdMenuLayout = new javax.swing.GroupLayout(IdMenu);
        IdMenu.setLayout(IdMenuLayout);
        IdMenuLayout.setHorizontalGroup(
            IdMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(IdMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(IdMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        IdMenuLayout.setVerticalGroup(
            IdMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(IdMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        idSideBorder.setBackground(new java.awt.Color(56, 23, 62));
        idSideBorder.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout idSideBorderLayout = new javax.swing.GroupLayout(idSideBorder);
        idSideBorder.setLayout(idSideBorderLayout);
        idSideBorderLayout.setHorizontalGroup(
            idSideBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        idSideBorderLayout.setVerticalGroup(
            idSideBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PlateSideBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(309, 309, 309))
            .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MenuPanelLayout.createSequentialGroup()
                    .addComponent(idSideBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 559, Short.MAX_VALUE)))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addComponent(PlateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(IdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PlateSideBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(294, Short.MAX_VALUE))
            .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MenuPanelLayout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(idSideBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );

        sidePanel.add(MenuPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(sidePanel, java.awt.BorderLayout.LINE_START);

        Mainview.setPreferredSize(new java.awt.Dimension(800, 500));
        Mainview.setLayout(new java.awt.BorderLayout());

        plateView.setBackground(new java.awt.Color(146, 61, 161));
        plateView.setPreferredSize(new java.awt.Dimension(800, 500));

        javax.swing.GroupLayout plateViewLayout = new javax.swing.GroupLayout(plateView);
        plateView.setLayout(plateViewLayout);
        plateViewLayout.setHorizontalGroup(
            plateViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        plateViewLayout.setVerticalGroup(
            plateViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Mainview.add(plateView, java.awt.BorderLayout.CENTER);

        idView.setBackground(new java.awt.Color(188, 177, 190));
        idView.setMaximumSize(new java.awt.Dimension(800, 500));
        idView.setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        im1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        im1.setPreferredSize(new java.awt.Dimension(192, 192));
        jPanel3.add(im1);

        im2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        im2.setPreferredSize(new java.awt.Dimension(192, 192));
        jPanel3.add(im2);

        im3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        im3.setPreferredSize(new java.awt.Dimension(192, 192));
        jPanel3.add(im3);

        im4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        im4.setPreferredSize(new java.awt.Dimension(192, 192));
        jPanel3.add(im4);

        printBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        printBtn.setText("Print");
        printBtn.setActionCommand("Print");
        printBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        printBtn.setEnabled(false);
        printBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printBtnMouseClicked(evt);
            }
        });

        uploadBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        uploadBtn.setText("Upload");
        uploadBtn.setBorderPainted(false);
        uploadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(463, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(printBtn)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(407, Short.MAX_VALUE)
                    .addComponent(uploadBtn)
                    .addGap(26, 26, 26)))
        );

        javax.swing.GroupLayout idViewLayout = new javax.swing.GroupLayout(idView);
        idView.setLayout(idViewLayout);
        idViewLayout.setHorizontalGroup(
            idViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        idViewLayout.setVerticalGroup(
            idViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Mainview.add(idView, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(Mainview, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private JPanel selectedPanel = null;
    private JPanel selectedBorder = null;
    private JPanel mainViewPanel = null;
    
    
    public void uploadImage()
    {
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image", "jpg", "jpeg", "png");
        fileChooser.setFileFilter(filter);
        
        int result = fileChooser.showOpenDialog(null);
                if(result == JFileChooser.APPROVE_OPTION)
                {
                    File selectedFile = fileChooser.getSelectedFile();
                    
                    ImageIcon image = new ImageIcon(selectedFile.getAbsolutePath());
                    Image resize = image.getImage().getScaledInstance(im1.getWidth(), im1.getHeight(), Image.SCALE_SMOOTH);
                    image = new ImageIcon(resize);
                    im1.setIcon(image);
                    im2.setIcon(image);
                    im3.setIcon(image);
                    im4.setIcon(image);
                    printBtn.setEnabled(true);
                }
        
    }
    public void selectedMenu(JPanel panel, JPanel sideBorder, JPanel mainView)
    {
         
        if(selectedPanel != null)
        {
            selectedPanel.setBackground(new Color(56, 23, 62));
            selectedBorder.setBackground(new Color(56, 23, 62));
            mainViewPanel.setVisible(false);
        }else{
            mainView.setVisible(false);
        }
        
        
        panel.setBackground(new Color(169, 71, 187));
        sideBorder.setBackground(new Color(112, 47, 124));
        selectedPanel = panel;
        selectedBorder = sideBorder;
        mainViewPanel = mainView;
        mainView.setVisible(true);
    }
    
    public void hover(JPanel panel, Color panelColor, JPanel sideBorder, Color sideBorderColor)
    {
        if(selectedPanel != panel)
        {
            panel.setBackground(panelColor);
            sideBorder.setBackground(sideBorderColor);
        }
    }
    public void removeHover(JPanel panel, Color panelColor, JPanel sideBorder)
    {
        if(selectedPanel != panel)
        {
            panel.setBackground(panelColor);
            sideBorder.setBackground(panelColor);
        }
    }
    private void PlateMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlateMenuMouseEntered
        //Change color of panel and sideBorder
        hover(PlateMenu, new Color(197, 132, 209), PlateSideBorder, new Color(169, 71, 187));
    }//GEN-LAST:event_PlateMenuMouseEntered

    private void PlateMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlateMenuMouseExited
          //Remove color of panel and sideBorder
          removeHover(PlateMenu, new Color(56, 23, 62), PlateSideBorder);
    }//GEN-LAST:event_PlateMenuMouseExited

    private void IdMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdMenuMouseEntered
      hover(IdMenu, new Color(197, 132, 209), idSideBorder, new Color(169, 71, 187));
    }//GEN-LAST:event_IdMenuMouseEntered

    private void IdMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdMenuMouseExited
        removeHover(IdMenu, new Color(56, 23, 62), idSideBorder);
    }//GEN-LAST:event_IdMenuMouseExited

    private void IdMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdMenuMouseClicked
       
        selectedMenu(IdMenu, idSideBorder, idView);
    }//GEN-LAST:event_IdMenuMouseClicked

    private void PlateMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlateMenuMouseClicked
       selectedMenu(PlateMenu, PlateSideBorder, plateView);
    }//GEN-LAST:event_PlateMenuMouseClicked

    private void printBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBtnMouseClicked
       
    }//GEN-LAST:event_printBtnMouseClicked

    private void uploadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadBtnMouseClicked
        // TODO add your handling code here:
        uploadImage();
    }//GEN-LAST:event_uploadBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IdMenu;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JPanel Mainview;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel PlateMenu;
    private javax.swing.JPanel PlateSideBorder;
    private javax.swing.JPanel idSideBorder;
    private javax.swing.JPanel idView;
    private javax.swing.JLabel im1;
    private javax.swing.JLabel im2;
    private javax.swing.JLabel im3;
    private javax.swing.JLabel im4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel plateView;
    private javax.swing.JButton printBtn;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton uploadBtn;
    // End of variables declaration//GEN-END:variables
}
